import type { Locale } from '@/i18n/config';

export const COPY = {
  ru: {
    linked: 'Готово, Telegram подключён к Personal Hub. Используйте кнопки меню ниже.',
    invalidToken: 'Код привязки недействителен или истёк. Сгенерируй новый код в Settings → Telegram.',
    notLinked: 'Сначала подключи Telegram в Personal Hub: Settings → Telegram, затем отправь /start с кодом.',
    help: 'Используйте кнопки меню внизу экрана. Текстовые команды тоже работают.',
    promptAddTask: 'Напишите название нового дела:',
    promptAddExpense: 'Отправьте: сумма название (например: 5 энергетики)',
    promptExpenseCategory: 'Выберите категорию расхода:',
    promptAddIncome: 'Отправьте: сумма название (например: 1000 Зарплата)',
    promptRename: 'Напишите новое название:',
    promptDue: 'Отправьте дату в формате YYYY-MM-DD:',
    promptAmount: 'Отправьте новую сумму:',
    promptNote: 'Отправьте новую заметку:',
    promptDate: 'Отправьте дату YYYY-MM-DD:',
    promptBudget: 'Отправьте новый лимит бюджета:',
    promptCardPay: 'Отправьте сумму оплаты:',
    emptyTasks: 'Открытых дел пока нет.',
    emptyDoneTasks: 'Выполненных дел пока нет.',
    added: 'Добавил дело:',
    updated: 'Обновил дело:',
    deleted: 'Удалил дело:',
    taskNotFound: 'Дело не найдено.',
    dailyTitle: 'Напоминание на сегодня',
    noDailyTasks: 'На сегодня открытых дел нет.',
    tasksTitle: 'Открытые дела',
    doneTasksTitle: 'Выполненные дела',
    invalidCommand: 'Не понял. Выберите кнопку в меню.',
    invalidDate: 'Неверная дата. Используй формат YYYY-MM-DD.',
    invalidAmount: 'Неверная сумма.',
    txAdded: 'Добавил транзакцию:',
    txUpdated: 'Обновил транзакцию.',
    txDeleted: 'Удалил транзакцию.',
    txNotFound: 'Транзакция не найдена.',
    txListTitle: 'Последние транзакции',
    emptyTx: 'Транзакций пока нет.',
    finTitle: 'Финансовый отчёт',
    budgetListTitle: 'Бюджеты',
    emptyBudgets: 'Бюджетов пока нет.',
    budgetSet: 'Бюджет обновлён:',
    categoryNotFound: 'Категория не найдена.',
    cardsTitle: 'Кредитки',
    emptyCards: 'Кредиток пока нет.',
    cardAdded: 'Кредитка добавлена:',
    cardPaid: 'Оплата кредитки записана:',
    cardArchived: 'Кредитка архивирована:',
    cardNotFound: 'Кредитка не найдена.',
    actionDone: 'Готово',
  },
  en: {
    linked: 'Done, Telegram is connected to Personal Hub. Use the menu buttons below.',
    invalidToken: 'The link code is invalid or expired. Generate a new code in Settings → Telegram.',
    notLinked: 'Connect Telegram in Personal Hub first: Settings → Telegram, then send /start with the code.',
    help: 'Use the menu buttons at the bottom. Text commands still work too.',
    promptAddTask: 'Send the new task title:',
    promptAddExpense: 'Send: amount name (e.g. 5 energy drinks)',
    promptExpenseCategory: 'Choose an expense category:',
    promptAddIncome: 'Send: amount name (e.g. 1000 Salary)',
    promptRename: 'Send the new title:',
    promptDue: 'Send date as YYYY-MM-DD:',
    promptAmount: 'Send the new amount:',
    promptNote: 'Send the new note:',
    promptDate: 'Send date YYYY-MM-DD:',
    promptBudget: 'Send the new budget limit:',
    promptCardPay: 'Send payment amount:',
    emptyTasks: 'No open tasks yet.',
    emptyDoneTasks: 'No completed tasks yet.',
    added: 'Added task:',
    updated: 'Updated task:',
    deleted: 'Deleted task:',
    taskNotFound: 'Task not found.',
    dailyTitle: 'Daily reminder',
    noDailyTasks: 'No open tasks for today.',
    tasksTitle: 'Open tasks',
    doneTasksTitle: 'Completed tasks',
    invalidCommand: 'Unknown action. Use the menu buttons.',
    invalidDate: 'Invalid date. Use YYYY-MM-DD.',
    invalidAmount: 'Invalid amount.',
    txAdded: 'Added transaction:',
    txUpdated: 'Updated transaction.',
    txDeleted: 'Deleted transaction.',
    txNotFound: 'Transaction not found.',
    txListTitle: 'Recent transactions',
    emptyTx: 'No transactions yet.',
    finTitle: 'Finance report',
    budgetListTitle: 'Budgets',
    emptyBudgets: 'No budgets yet.',
    budgetSet: 'Budget updated:',
    categoryNotFound: 'Category not found.',
    cardsTitle: 'Credit cards',
    emptyCards: 'No credit cards yet.',
    cardAdded: 'Credit card added:',
    cardPaid: 'Credit card payment recorded:',
    cardArchived: 'Credit card archived:',
    cardNotFound: 'Credit card not found.',
    actionDone: 'Done',
  },
} satisfies Record<Locale, Record<string, string>>;

