import type { Locale } from '@/i18n/config';

export const COPY = {
  ru: {
    linked: 'Готово, Telegram подключён к Personal Hub. Отправь /help, чтобы увидеть команды.',
    invalidToken: 'Код привязки недействителен или истёк. Сгенерируй новый код в Settings → Telegram.',
    notLinked: 'Сначала подключи Telegram в Personal Hub: Settings → Telegram, затем отправь /start с кодом.',
    help: [
      'Команды Personal Hub:',
      '',
      'Задачи:',
      '/tasks — открытые дела',
      '/tasks done — выполненные',
      '/task add Купить молоко',
      '/task done 3',
      '/task start 3',
      '/task edit 3 Новый текст',
      '/task due 3 2026-06-15',
      '/task delete 3',
      'Любое обычное сообщение тоже добавляет дело.',
      '',
      'Финансы:',
      '/fin — отчёт за период',
      '/tx list — последние транзакции',
      '/tx add expense 12.50 Еда Обед',
      '/tx add income 1000 Зарплата',
      '/tx edit 2 amount 15.00',
      '/tx edit 2 note Новый текст',
      '/tx delete 2',
      '/budget list',
      '/budget set Еда 300',
      '/cards',
      '/card add Visa 5000',
      '/card pay 1 100',
      '/card archive 1',
    ].join('\n'),
    emptyTasks: 'Открытых дел пока нет.',
    emptyDoneTasks: 'Выполненных дел пока нет.',
    added: 'Добавил дело:',
    updated: 'Обновил дело:',
    deleted: 'Удалил дело:',
    taskNotFound: 'Дело не найдено. Сначала отправь /tasks.',
    dailyTitle: 'Напоминание на сегодня',
    noDailyTasks: 'На сегодня открытых дел нет.',
    tasksTitle: 'Открытые дела',
    doneTasksTitle: 'Выполненные дела',
    invalidCommand: 'Не понял команду. Отправь /help.',
    invalidDate: 'Неверная дата. Используй формат YYYY-MM-DD.',
    invalidAmount: 'Неверная сумма.',
    txAdded: 'Добавил транзакцию:',
    txUpdated: 'Обновил транзакцию:',
    txDeleted: 'Удалил транзакцию:',
    txNotFound: 'Транзакция не найдена. Сначала отправь /tx list.',
    txListTitle: 'Последние транзакции',
    emptyTx: 'Транзакций пока нет.',
    finTitle: 'Финансовый отчёт',
    budgetListTitle: 'Бюджеты',
    emptyBudgets: 'Бюджетов пока нет.',
    budgetSet: 'Бюджет обновлён:',
    categoryNotFound: 'Категория не найдена.',
    cardsTitle: 'Кредитки',
    emptyCards: 'Кредиток пока нет.',
    cardAdded: 'Кредитка добавлена:',
    cardPaid: 'Оплата кредитки записана:',
    cardArchived: 'Кредитка архивирована:',
    cardNotFound: 'Кредитка не найдена. Сначала отправь /cards.',
  },
  en: {
    linked: 'Done, Telegram is connected to Personal Hub. Send /help to see commands.',
    invalidToken: 'The link code is invalid or expired. Generate a new code in Settings → Telegram.',
    notLinked: 'Connect Telegram in Personal Hub first: Settings → Telegram, then send /start with the code.',
    help: [
      'Personal Hub commands:',
      '',
      'Tasks:',
      '/tasks — open tasks',
      '/tasks done — completed tasks',
      '/task add Buy milk',
      '/task done 3',
      '/task start 3',
      '/task edit 3 New title',
      '/task due 3 2026-06-15',
      '/task delete 3',
      'Any regular message is also added as a task.',
      '',
      'Finance:',
      '/fin — period report',
      '/tx list — recent transactions',
      '/tx add expense 12.50 Food Lunch',
      '/tx add income 1000 Salary',
      '/tx edit 2 amount 15.00',
      '/tx edit 2 note New text',
      '/tx delete 2',
      '/budget list',
      '/budget set Food 300',
      '/cards',
      '/card add Visa 5000',
      '/card pay 1 100',
      '/card archive 1',
    ].join('\n'),
    emptyTasks: 'No open tasks yet.',
    emptyDoneTasks: 'No completed tasks yet.',
    added: 'Added task:',
    updated: 'Updated task:',
    deleted: 'Deleted task:',
    taskNotFound: 'Task not found. Send /tasks first.',
    dailyTitle: 'Daily reminder',
    noDailyTasks: 'No open tasks for today.',
    tasksTitle: 'Open tasks',
    doneTasksTitle: 'Completed tasks',
    invalidCommand: 'Unknown command. Send /help.',
    invalidDate: 'Invalid date. Use YYYY-MM-DD.',
    invalidAmount: 'Invalid amount.',
    txAdded: 'Added transaction:',
    txUpdated: 'Updated transaction:',
    txDeleted: 'Deleted transaction:',
    txNotFound: 'Transaction not found. Send /tx list first.',
    txListTitle: 'Recent transactions',
    emptyTx: 'No transactions yet.',
    finTitle: 'Finance report',
    budgetListTitle: 'Budgets',
    emptyBudgets: 'No budgets yet.',
    budgetSet: 'Budget updated:',
    categoryNotFound: 'Category not found.',
    cardsTitle: 'Credit cards',
    emptyCards: 'No credit cards yet.',
    cardAdded: 'Credit card added:',
    cardPaid: 'Credit card payment recorded:',
    cardArchived: 'Credit card archived:',
    cardNotFound: 'Credit card not found. Send /cards first.',
  },
} satisfies Record<Locale, Record<string, string>>;
